import { createContext, useContext, useEffect, useMemo, useState } from "react";

const languages = {
  fr: "FR",
  en: "EN",
  ar: "AR",
  es: "ES"
};

const translations = {
  fr: {
    brandSubtitle: "Détection intelligente",
    navHome: "Accueil",
    navAnalysis: "Analyse d'image",
    navHistory: "Historique",
    navReports: "Rapports",
    navSettings: "Paramètres",
    navAbout: "À propos",
    headerTitle: "Détection de Pneumonie par IA",
    headerSubtitle: "Analyse de radiographies thoraciques avec contrôle de qualité et détection multi-pathologies",
    lightMode: "Mode clair",
    darkMode: "Mode sombre",
    sidebarAboutTitle: "À propos du système",
    sidebarAboutText: "Ce système analyse une radiographie thoracique en 2 étapes :",
    sidebarQuality: "1. Évaluation de la qualité",
    sharpness: "Netteté (détection flou)",
    brightness: "Luminosité (exposition)",
    contrast: "Contraste",
    sidebarDiagnosis: "2. Diagnostic multi-pathologies",
    sidebarModel: "Modèle : MobileNetV2",
    sidebarClasses: "4 classes détectées",
    sidebarAid: "Système d'aide à la décision",
    sidebarAidText: "Un outil d'aide fiable pour les professionnels de santé dans l'analyse des radiographies thoraciques.",
    learnMore: "En savoir plus →",
    version: "Version 2.0.0",
    heroTitle: "PneumoAI",
    heroLead: "Détection intelligente des maladies pulmonaires",
    heroText: "PneumoAI utilise l'intelligence artificielle pour analyser les radiographies thoraciques et détecter plusieurs pathologies pulmonaires avec précision et rapidité.",
    startAnalysis: "Commencer une analyse",
    pneumoniaCard: "Détection de Pneumonie",
    pneumoniaText: "Identification des signes de pneumonie avec évaluation du niveau de probabilité.",
    effusionCard: "Détection d'Épanchement pleural",
    effusionText: "Détection et évaluation des épanchements pleuraux (liquide dans la plèvre).",
    consolidationCard: "Détection de Consolidation",
    consolidationText: "Identification des zones de consolidation dans le parenchyme pulmonaire.",
    statAccuracy: "Précision du modèle",
    statAccuracyText: "Sur l'ensemble des prédictions",
    statTime: "Temps moyen d'analyse",
    statTimeText: "Rapide et efficace",
    statImages: "Radiographies analysées",
    statImagesText: "Données traitées avec succès",
    trustTitle: "Sécurisé · Rapide · Fiable",
    trustText: "PneumoAI est conçu pour assister les professionnels de santé dans la prise de décision.",
    analysisInfo: "Le système détecte 4 pathologies : Pneumonie, Épanchement pleural, Consolidation et Normal",
    apiLoading: "Analyse de l'image en cours via l'API FastAPI...",
    apiError: "API indisponible ou erreur d'analyse. Aucun résultat n'est affiché tant que l'analyse réelle n'a pas réussi.",
    uploadTitle: "Uploader une radiographie",
    previewTitle: "Aperçu de l'image",
    qualityTitle: "Qualité de l'image",
    diagnosisTitle: "Résultat du diagnostic (Multi-pathologies)",
    historyTitle: "Historique des analyses",
    historyDesc: "Consultez les analyses récentes et leurs décisions associées.",
    totalAnalyses: "Analyses totales",
    reliableDiagnoses: "Diagnostics fiables",
    toReview: "À vérifier",
    latestXrays: "Dernières radiographies analysées",
    search: "Rechercher",
    reportsTitle: "Rapports",
    reportsDesc: "Générez et consultez les rapports liés aux analyses réelles.",
    availableReports: "Rapports disponibles",
    clinicalSummary: "Résumé clinique",
    cautiousDiagnosis: "Diagnostic avec prudence",
    clinicalText: "Les résultats affichés proviennent du modèle multi-label V2. Une validation médicale reste nécessaire.",
    noHistory: "Aucune analyse réelle n'a encore été enregistrée dans cette session.",
    waitingAnalysis: "En attente d'une analyse réelle",
    realResultsText: "Les probabilités seront générées après l'envoi d'une radiographie à l'API FastAPI.",
    settingsTitle: "Paramètres",
    settingsDesc: "Configurez l'expérience de démonstration de PneumoAI.",
    generalPrefs: "Préférences générales",
    notifications: "Notifications",
    notificationsText: "Recevoir une alerte lorsqu'un rapport est prêt.",
    medicalValidation: "Validation médicale",
    medicalValidationText: "Afficher un rappel de validation par radiologue.",
    demoMode: "Mode démonstration",
    demoModeText: "Utiliser des données fictives sur les pages secondaires.",
    apiConfig: "Configuration API",
    saveSettings: "Enregistrer les paramètres",
    aboutTitle: "À propos",
    aboutDesc: "Informations générales sur le système d'aide à la décision PneumoAI.",
    aboutBody: "PneumoAI est une interface de démonstration pour l'analyse de radiographies thoraciques, avec contrôle de qualité et restitution visuelle des probabilités.",
    currentFlow: "Fonctionnement actuel",
    medicalWarning: "Avertissement médical",
    warningText: "Ce système ne remplace pas un diagnostic médical. Les résultats doivent toujours être interprétés et validés par un professionnel de santé qualifié."
    ,uploadDrop: "Glissez-déposez votre image ici",
    orText: "ou",
    chooseFile: "Choisir un fichier",
    acceptedFormats: "Formats acceptés : JPEG, PNG",
    maxSize: "Taille maximale : 20MB",
    imageLoaded: "Image chargée avec succès",
    qualityEnough: "Qualité suffisante pour l'analyse",
    howWorks: "Comment ça marche ?",
    stepUpload: "Upload",
    stepUploadText: "Uploadez une radiographie thoracique (JPEG ou PNG).",
    stepAnalyze: "Analyse",
    stepAnalyzeText: "Le système évalue la qualité de l'image et détecte les pathologies",
    stepDecision: "Décision",
    stepDecisionText: "Diagnostic multi-pathologies avec niveau de confiance et recommandation",
    decisionLabel: "Décision : Diagnostic avec prudence",
    decisionText: "Plusieurs anomalies détectées. Veuillez consulter un professionnel de santé.",
    reportButton: "Voir le rapport détaillé",
    probHigh: "Probabilité élevée",
    probModerate: "Probabilité modérée",
    probLow: "Probabilité faible"
  },
  en: {
    brandSubtitle: "Intelligent detection",
    navHome: "Home",
    navAnalysis: "Image analysis",
    navHistory: "History",
    navReports: "Reports",
    navSettings: "Settings",
    navAbout: "About",
    headerTitle: "AI Pneumonia Detection",
    headerSubtitle: "Chest X-ray analysis with quality control and multi-pathology detection",
    lightMode: "Light mode",
    darkMode: "Dark mode",
    sidebarAboutTitle: "About the system",
    sidebarAboutText: "This system analyzes a chest X-ray in 2 steps:",
    sidebarQuality: "1. Quality assessment",
    sharpness: "Sharpness (blur detection)",
    brightness: "Brightness (exposure)",
    contrast: "Contrast",
    sidebarDiagnosis: "2. Multi-pathology diagnosis",
    sidebarModel: "Model: MobileNetV2",
    sidebarClasses: "4 detected classes",
    sidebarAid: "Decision support system",
    sidebarAidText: "A reliable support tool for healthcare professionals analyzing chest X-rays.",
    learnMore: "Learn more →",
    version: "Version 2.0.0",
    heroTitle: "PneumoAI",
    heroLead: "Intelligent lung disease detection",
    heroText: "PneumoAI uses artificial intelligence to analyze chest X-rays and detect multiple pulmonary pathologies quickly and accurately.",
    startAnalysis: "Start an analysis",
    pneumoniaCard: "Pneumonia detection",
    pneumoniaText: "Identification of pneumonia signs with probability level assessment.",
    effusionCard: "Pleural effusion detection",
    effusionText: "Detection and evaluation of pleural effusions (fluid in the pleura).",
    consolidationCard: "Consolidation detection",
    consolidationText: "Identification of consolidation areas in the pulmonary parenchyma.",
    statAccuracy: "Model accuracy",
    statAccuracyText: "Across all predictions",
    statTime: "Average analysis time",
    statTimeText: "Fast and efficient",
    statImages: "X-rays analyzed",
    statImagesText: "Data processed successfully",
    trustTitle: "Secure · Fast · Reliable",
    trustText: "PneumoAI is designed to assist healthcare professionals in decision-making.",
    analysisInfo: "The system detects 4 pathologies: Pneumonia, Pleural effusion, Consolidation and Normal",
    apiLoading: "Image analysis in progress via the FastAPI API...",
    apiError: "API unavailable or analysis error. No result is shown until the real analysis succeeds.",
    uploadTitle: "Upload an X-ray",
    previewTitle: "Image preview",
    qualityTitle: "Image quality",
    diagnosisTitle: "Diagnostic result (Multi-pathology)",
    historyTitle: "Analysis history",
    historyDesc: "Review recent analyses and their related decisions.",
    totalAnalyses: "Total analyses",
    reliableDiagnoses: "Reliable diagnoses",
    toReview: "To review",
    latestXrays: "Latest analyzed X-rays",
    search: "Search",
    reportsTitle: "Reports",
    reportsDesc: "Generate and view reports related to real analyses.",
    availableReports: "Available reports",
    clinicalSummary: "Clinical summary",
    cautiousDiagnosis: "Cautious diagnosis",
    clinicalText: "Displayed results come from the V2 multi-label model. Medical validation remains necessary.",
    noHistory: "No real analysis has been recorded in this session yet.",
    waitingAnalysis: "Waiting for a real analysis",
    realResultsText: "Probabilities will be generated after sending a chest X-ray to the FastAPI backend.",
    settingsTitle: "Settings",
    settingsDesc: "Configure the PneumoAI demonstration experience.",
    generalPrefs: "General preferences",
    notifications: "Notifications",
    notificationsText: "Receive an alert when a report is ready.",
    medicalValidation: "Medical validation",
    medicalValidationText: "Show a reminder for radiologist validation.",
    demoMode: "Demo mode",
    demoModeText: "Use real analysis data on secondary pages.",
    apiConfig: "API configuration",
    saveSettings: "Save settings",
    aboutTitle: "About",
    aboutDesc: "General information about the PneumoAI decision support system.",
    aboutBody: "PneumoAI is a demonstration interface for chest X-ray analysis, with quality control and visual probability reporting.",
    currentFlow: "Current workflow",
    medicalWarning: "Medical warning",
    warningText: "This system does not replace a medical diagnosis. Results must always be interpreted and validated by a qualified healthcare professional."
    ,uploadDrop: "Drag and drop your image here",
    orText: "or",
    chooseFile: "Choose a file",
    acceptedFormats: "Accepted formats: JPEG, PNG",
    maxSize: "Maximum size: 20MB",
    imageLoaded: "Image loaded successfully",
    qualityEnough: "Quality sufficient for analysis",
    howWorks: "How does it work?",
    stepUpload: "Upload",
    stepUploadText: "Upload a chest X-ray (JPEG or PNG).",
    stepAnalyze: "Analysis",
    stepAnalyzeText: "The system evaluates image quality and detects pathologies",
    stepDecision: "Decision",
    stepDecisionText: "Multi-pathology diagnosis with confidence level and recommendation",
    decisionLabel: "Decision: Cautious diagnosis",
    decisionText: "Several abnormalities detected. Please consult a healthcare professional.",
    reportButton: "View detailed report",
    probHigh: "High probability",
    probModerate: "Moderate probability",
    probLow: "Low probability"
  },
  ar: {
    brandSubtitle: "كشف ذكي",
    navHome: "الرئيسية",
    navAnalysis: "تحليل الصورة",
    navHistory: "السجل",
    navReports: "التقارير",
    navSettings: "الإعدادات",
    navAbout: "حول",
    headerTitle: "كشف الالتهاب الرئوي بالذكاء الاصطناعي",
    headerSubtitle: "تحليل صور الصدر بالأشعة مع مراقبة الجودة وكشف أمراض متعددة",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الداكن",
    sidebarAboutTitle: "حول النظام",
    sidebarAboutText: "يحلل هذا النظام صورة أشعة الصدر في خطوتين:",
    sidebarQuality: "1. تقييم الجودة",
    sharpness: "الوضوح (كشف الضبابية)",
    brightness: "الإضاءة (التعرض)",
    contrast: "التباين",
    sidebarDiagnosis: "2. تشخيص متعدد الأمراض",
    sidebarModel: "النموذج: MobileNetV2",
    sidebarClasses: "4 فئات مكتشفة",
    sidebarAid: "نظام دعم القرار",
    sidebarAidText: "أداة دعم موثوقة للمهنيين الصحيين في تحليل صور أشعة الصدر.",
    learnMore: "اعرف المزيد ←",
    version: "الإصدار 2.0.0",
    heroTitle: "PneumoAI",
    heroLead: "كشف ذكي لأمراض الرئة",
    heroText: "يستخدم PneumoAI الذكاء الاصطناعي لتحليل صور أشعة الصدر وكشف عدة أمراض رئوية بدقة وسرعة.",
    startAnalysis: "ابدأ التحليل",
    pneumoniaCard: "كشف الالتهاب الرئوي",
    pneumoniaText: "تحديد علامات الالتهاب الرئوي مع تقييم مستوى الاحتمال.",
    effusionCard: "كشف الانصباب الجنبي",
    effusionText: "كشف وتقييم الانصباب الجنبي (وجود سائل في الغشاء الجنبي).",
    consolidationCard: "كشف التكثف",
    consolidationText: "تحديد مناطق التكثف في نسيج الرئة.",
    statAccuracy: "دقة النموذج",
    statAccuracyText: "على جميع التنبؤات",
    statTime: "متوسط زمن التحليل",
    statTimeText: "سريع وفعال",
    statImages: "صور أشعة محللة",
    statImagesText: "تمت معالجة البيانات بنجاح",
    trustTitle: "آمن · سريع · موثوق",
    trustText: "صمم PneumoAI لمساعدة المهنيين الصحيين في اتخاذ القرار.",
    analysisInfo: "يكشف النظام 4 حالات: التهاب رئوي، انصباب جنبي، تكثف وطبيعي",
    apiLoading: "جاري تحليل الصورة عبر واجهة FastAPI...",
    apiError: "واجهة API غير متاحة أو حدث خطأ. لن يتم عرض أي نتيجة حتى ينجح التحليل الحقيقي.",
    uploadTitle: "رفع صورة أشعة",
    previewTitle: "معاينة الصورة",
    qualityTitle: "جودة الصورة",
    diagnosisTitle: "نتيجة التشخيص (متعدد الأمراض)",
    historyTitle: "سجل التحليلات",
    historyDesc: "راجع التحليلات الحديثة والقرارات المرتبطة بها.",
    totalAnalyses: "إجمالي التحليلات",
    reliableDiagnoses: "تشخيصات موثوقة",
    toReview: "للمراجعة",
    latestXrays: "آخر صور الأشعة المحللة",
    search: "بحث",
    reportsTitle: "التقارير",
    reportsDesc: "أنشئ وراجع التقارير المرتبطة بالتحليلات الحقيقية.",
    availableReports: "التقارير المتاحة",
    clinicalSummary: "ملخص سريري",
    cautiousDiagnosis: "تشخيص بحذر",
    clinicalText: "النتائج المعروضة صادرة عن نموذج V2 متعدد التسميات. تبقى المراجعة الطبية ضرورية.",
    noHistory: "لم يتم تسجيل أي تحليل حقيقي في هذه الجلسة بعد.",
    waitingAnalysis: "في انتظار تحليل حقيقي",
    realResultsText: "سيتم توليد الاحتمالات بعد إرسال صورة الأشعة إلى واجهة FastAPI.",
    settingsTitle: "الإعدادات",
    settingsDesc: "اضبط تجربة العرض الخاصة بـ PneumoAI.",
    generalPrefs: "التفضيلات العامة",
    notifications: "الإشعارات",
    notificationsText: "استلام تنبيه عندما يكون التقرير جاهزاً.",
    medicalValidation: "التحقق الطبي",
    medicalValidationText: "إظهار تذكير بالتحقق من طرف طبيب الأشعة.",
    demoMode: "وضع العرض",
    demoModeText: "استخدام بيانات تجريبية في الصفحات الثانوية.",
    apiConfig: "إعدادات API",
    saveSettings: "حفظ الإعدادات",
    aboutTitle: "حول",
    aboutDesc: "معلومات عامة حول نظام دعم القرار PneumoAI.",
    aboutBody: "PneumoAI واجهة عرض لتحليل صور أشعة الصدر مع مراقبة الجودة وعرض الاحتمالات بصرياً.",
    currentFlow: "طريقة العمل الحالية",
    medicalWarning: "تنبيه طبي",
    warningText: "هذا النظام لا يعوض التشخيص الطبي. يجب دائماً تفسير النتائج والتحقق منها من طرف مختص صحي مؤهل."
    ,uploadDrop: "اسحب الصورة وأفلتها هنا",
    orText: "أو",
    chooseFile: "اختر ملفاً",
    acceptedFormats: "الصيغ المقبولة: JPEG, PNG",
    maxSize: "الحجم الأقصى: 20MB",
    imageLoaded: "تم تحميل الصورة بنجاح",
    qualityEnough: "الجودة كافية للتحليل",
    howWorks: "كيف يعمل؟",
    stepUpload: "رفع",
    stepUploadText: "ارفع صورة أشعة صدر (JPEG أو PNG).",
    stepAnalyze: "تحليل",
    stepAnalyzeText: "يقيم النظام جودة الصورة ويكشف الأمراض",
    stepDecision: "قرار",
    stepDecisionText: "تشخيص متعدد الأمراض مع مستوى الثقة والتوصية",
    decisionLabel: "القرار: تشخيص بحذر",
    decisionText: "تم اكتشاف عدة مؤشرات. يرجى استشارة مختص صحي.",
    reportButton: "عرض التقرير المفصل",
    probHigh: "احتمال مرتفع",
    probModerate: "احتمال متوسط",
    probLow: "احتمال منخفض"
  },
  es: {
    brandSubtitle: "Detección inteligente",
    navHome: "Inicio",
    navAnalysis: "Análisis de imagen",
    navHistory: "Historial",
    navReports: "Informes",
    navSettings: "Configuración",
    navAbout: "Acerca de",
    headerTitle: "Detección de Neumonía con IA",
    headerSubtitle: "Análisis de radiografías torácicas con control de calidad y detección multipatología",
    lightMode: "Modo claro",
    darkMode: "Modo oscuro",
    sidebarAboutTitle: "Acerca del sistema",
    sidebarAboutText: "Este sistema analiza una radiografía torácica en 2 pasos:",
    sidebarQuality: "1. Evaluación de calidad",
    sharpness: "Nitidez (detección de desenfoque)",
    brightness: "Luminosidad (exposición)",
    contrast: "Contraste",
    sidebarDiagnosis: "2. Diagnóstico multipatología",
    sidebarModel: "Modelo: MobileNetV2",
    sidebarClasses: "4 clases detectadas",
    sidebarAid: "Sistema de apoyo a la decisión",
    sidebarAidText: "Una herramienta fiable para profesionales de salud en el análisis de radiografías torácicas.",
    learnMore: "Saber más →",
    version: "Versión 2.0.0",
    heroTitle: "PneumoAI",
    heroLead: "Detección inteligente de enfermedades pulmonares",
    heroText: "PneumoAI utiliza inteligencia artificial para analizar radiografías torácicas y detectar varias patologías pulmonares con precisión y rapidez.",
    startAnalysis: "Comenzar un análisis",
    pneumoniaCard: "Detección de Neumonía",
    pneumoniaText: "Identificación de signos de neumonía con evaluación del nivel de probabilidad.",
    effusionCard: "Detección de derrame pleural",
    effusionText: "Detección y evaluación de derrames pleurales (líquido en la pleura).",
    consolidationCard: "Detección de Consolidación",
    consolidationText: "Identificación de zonas de consolidación en el parénquima pulmonar.",
    statAccuracy: "Precisión del modelo",
    statAccuracyText: "En todas las predicciones",
    statTime: "Tiempo medio de análisis",
    statTimeText: "Rápido y eficaz",
    statImages: "Radiografías analizadas",
    statImagesText: "Datos procesados con éxito",
    trustTitle: "Seguro · Rápido · Fiable",
    trustText: "PneumoAI está diseñado para asistir a profesionales de salud en la toma de decisiones.",
    analysisInfo: "El sistema detecta 4 patologías: Neumonía, Derrame pleural, Consolidación y Normal",
    apiLoading: "Análisis de imagen en curso mediante la API FastAPI...",
    apiError: "API no disponible o error de análisis. No se muestra ningún resultado hasta que el análisis real finalice correctamente.",
    uploadTitle: "Subir una radiografía",
    previewTitle: "Vista previa",
    qualityTitle: "Calidad de imagen",
    diagnosisTitle: "Resultado del diagnóstico (Multipatología)",
    historyTitle: "Historial de análisis",
    historyDesc: "Consulta los análisis recientes y sus decisiones asociadas.",
    totalAnalyses: "Análisis totales",
    reliableDiagnoses: "Diagnósticos fiables",
    toReview: "Por revisar",
    latestXrays: "Últimas radiografías analizadas",
    search: "Buscar",
    reportsTitle: "Informes",
    reportsDesc: "Genera y consulta informes relacionados con análisis reales.",
    availableReports: "Informes disponibles",
    clinicalSummary: "Resumen clínico",
    cautiousDiagnosis: "Diagnóstico con prudencia",
    clinicalText: "Los resultados mostrados provienen del modelo multi-label V2. La validación médica sigue siendo necesaria.",
    noHistory: "Todavía no se ha registrado ningún análisis real en esta sesión.",
    waitingAnalysis: "Esperando un análisis real",
    realResultsText: "Las probabilidades se generarán después de enviar una radiografía al backend FastAPI.",
    settingsTitle: "Configuración",
    settingsDesc: "Configura la experiencia de demostración de PneumoAI.",
    generalPrefs: "Preferencias generales",
    notifications: "Notificaciones",
    notificationsText: "Recibir una alerta cuando un informe esté listo.",
    medicalValidation: "Validación médica",
    medicalValidationText: "Mostrar un recordatorio de validación por radiólogo.",
    demoMode: "Modo demostración",
    demoModeText: "Usar datos ficticios en páginas secundarias.",
    apiConfig: "Configuración API",
    saveSettings: "Guardar configuración",
    aboutTitle: "Acerca de",
    aboutDesc: "Información general sobre el sistema de apoyo a la decisión PneumoAI.",
    aboutBody: "PneumoAI es una interfaz de demostración para el análisis de radiografías torácicas, con control de calidad y visualización de probabilidades.",
    currentFlow: "Funcionamiento actual",
    medicalWarning: "Advertencia médica",
    warningText: "Este sistema no sustituye un diagnóstico médico. Los resultados siempre deben ser interpretados y validados por un profesional de salud cualificado."
    ,uploadDrop: "Arrastra y suelta tu imagen aquí",
    orText: "o",
    chooseFile: "Elegir un archivo",
    acceptedFormats: "Formatos aceptados: JPEG, PNG",
    maxSize: "Tamaño máximo: 20MB",
    imageLoaded: "Imagen cargada correctamente",
    qualityEnough: "Calidad suficiente para el análisis",
    howWorks: "¿Cómo funciona?",
    stepUpload: "Subida",
    stepUploadText: "Sube una radiografía torácica (JPEG o PNG).",
    stepAnalyze: "Análisis",
    stepAnalyzeText: "El sistema evalúa la calidad de imagen y detecta patologías",
    stepDecision: "Decisión",
    stepDecisionText: "Diagnóstico multipatología con nivel de confianza y recomendación",
    decisionLabel: "Decisión: Diagnóstico con prudencia",
    decisionText: "Varias anomalías detectadas. Consulta a un profesional de salud.",
    reportButton: "Ver informe detallado",
    probHigh: "Probabilidad alta",
    probModerate: "Probabilidad moderada",
    probLow: "Probabilidad baja"
  }
};

const AppContext = createContext(null);

export function AppProvider({ children }) {
  const [theme, setTheme] = useState(() => localStorage.getItem("pneumo-theme") || "light");
  const [language, setLanguage] = useState(() => localStorage.getItem("pneumo-language") || "fr");

  useEffect(() => {
    localStorage.setItem("pneumo-theme", theme);
    document.documentElement.classList.toggle("dark", theme === "dark");
  }, [theme]);

  useEffect(() => {
    localStorage.setItem("pneumo-language", language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const value = useMemo(() => {
    const dictionary = translations[language] ?? translations.fr;
    return {
      language,
      languages,
      setLanguage,
      theme,
      toggleTheme: () => setTheme((current) => (current === "dark" ? "light" : "dark")),
      t: (key) => dictionary[key] ?? translations.fr[key] ?? key
    };
  }, [language, theme]);

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
}

export function useApp() {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error("useApp must be used inside AppProvider");
  }
  return context;
}
